[package]
name = "scopedb-client"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "54.2.0"
base64 = "0.22.1"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.42.1", features = ["json"] }
