[linters]
disable-all = true
enable = [
  # TODO(tisonkun): enable once https://github.com/timakin/bodyclose/issues/60 resolved
  #  "bodyclose",
  "canonicalheader",
  "durationcheck",
  "errcheck",
  "errorlint",
  "exhaustive",
  "gofmt",
  "gofumpt",
  "goimports",
  "gomoddirectives",
  "gosec",
  "gosimple",
  "gosmopolitan",
  "govet",
  "ineffassign",
  "misspell",
  "nilerr",
  "staticcheck",
  "unused",
]
